# this file is autogenerated by .github/workflows/update.yml
{
  url = "https://github.com/TechStylex/nix-index-database/releases/download/2025-06-25-024801/index-";
  hashes = {
    x86_64-linux = "";
  };
}
