# this file is autogenerated by .github/workflows/update.yml
{
  url = "https://github.com/TechStylex/nix-index-database/releases/download/2024-06-25-022406/index-";
  hashes = {
    x86_64-linux = "";
  };
}
